version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: Star-Rental-Postgres
    environment:
      POSTGRES_DB: star_rental
      POSTGRES_USER: dev123
      POSTGRES_PASSWORD: dev123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../plano-software/set.sql:/docker-entrypoint-initdb.d/set.sql

volumes:
  postgres_data: