spring.application.name=starship-rental

# ===== DataSource PostgreSQL =====
spring.datasource.url=jdbc:postgresql://localhost:5433/star_rental
spring.datasource.username=dev123
spring.datasource.password=dev123

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



